require conf/distro/poky.conf

DISTRO = "ubuntu-tiny"
DISTRO_NAME = "Renesas Tiny"
DISTRO_VERSION = "5.1"

# remove all extra packages
POKY_DEFAULT_EXTRA_RDEPENDS = ""
POKY_DEFAULT_EXTRA_RRECOMMENDS = ""

# skip sanity checking
SKIP_META_VIRT_SANITY_CHECK = "1"
SKIP_META_SECURITY_SANITY_CHECK = "1"
SKIP_META_TPM_SANITY_CHECK = "1"

# Just need those features to build
DISTRO_FEATURES = "largefile wayland multiarch bluetooth opengl x11"

# Disable python usage in opkg-utils since it won't build with tiny config
PACKAGECONFIG:remove:pn-opkg-utils = "python"

# Enable libgstalsa.so for gstreamer
PACKAGECONFIG:append:pn-gstreamer1.0-plugins-base = " alsa"
